apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techfixer-ingress
  namespace: "2401029"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host:  2401029.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: techfixer-service
                port:
                  number: 8081
