apiVersion: v1
kind: Service
metadata:
  name: techfixer-service
  namespace: "2401029"
spec:
  selector:
    app: techfixer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
